# Generated by Django 4.2.7 on 2024-05-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='consultant',
        ),
        migrations.DeleteModel(
            name='Consultant',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
